name: Build

on:
  push:
    branches: [master]
  merge_group:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max_old_space_size=8192"

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Validate current commit (last commit) with commitlint
        run: bunx commitlint --last --verbose

      - name: Lint
        run: bun run lint

      - name: Format
        run: bun run format

  build:
    name: Build the project
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Build Next.js App
        run: bun run build
        env:
          NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
          NEXT_PUBLIC_SANITY_PROJECT_ID: qqvmmpgb
          NEXT_PUBLIC_SANITY_DATASET: test
          NEXT_PUBLIC_BASE_URL: https://www.redotengine.org
